version: "3"

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devops123
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana

  custom-es-exporter:
    container_name: custom-es-exporter
    build: ./custom-es-exporter
    # Specify which exporter you want to run like example-0.py.
    command: python exporters/clusterhealth_exporter.py
    ports:
      - 8000:8000
    volumes:
      - ./custom-exporter:/custom-exporter

volumes:
  grafana_data: