import os

from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.environ.get("ELASTIC_PASSWORD")

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="/escerts/certs/ca/ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())
# {'name': 'instance-0000000000', 'cluster_name': ...}

print("-"*40)
# Get cluster health
print(client.cluster.health())

print("-"*40)
# # Get node statistics (response is so long)
# print(client.nodes.stats())