---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: elastic-custom-exporter
  static_configs:
  - targets: ["elastic-custom-exporter:8000"]